/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import java.sql.*;
import conexion.Conectar;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class EditarUsuario extends javax.swing.JFrame {

    String user, usuario;
    int ID = 0;
    
    public EditarUsuario() {
        initComponents();
        user = Login.user;
        usuario = InformacionUsuario.usuario;
        
        setSize(600,450);
        setTitle("Edicion del usuario " + usuario + " - sesion de " + user);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection cn = Conectar.DataBase();
            PreparedStatement pst = cn.prepareStatement("select * from usuarios where alias = '" + usuario + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                ID = rs.getInt("id_usuario");
                txt_alias.setText(rs.getString("alias"));
                txt_dir.setText(rs.getString("direccion"));
                txt_nom.setText(rs.getString("nombre_usuario"));
                txt_pass.setText(rs.getString("pass"));
                txt_tel.setText(rs.getString("telefono"));
                cmb_estatus.setSelectedItem(rs.getString("estatus"));
            }
            cn.close();
            
        } catch (SQLException e) {
            System.err.println("error al cargar el usuario " + e);
        }
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LLaves.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_nom = new javax.swing.JTextField();
        txt_dir = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_alias = new javax.swing.JTextField();
        txt_pass = new javax.swing.JTextField();
        cmb_estatus = new javax.swing.JComboBox<>();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Direccion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alias:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estatus:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 210, 30));

        txt_nom.setBackground(new java.awt.Color(13, 71, 161));
        txt_nom.setForeground(new java.awt.Color(255, 255, 255));
        txt_nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 30));

        txt_dir.setBackground(new java.awt.Color(13, 71, 161));
        txt_dir.setForeground(new java.awt.Color(255, 255, 255));
        txt_dir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_dir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_dir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 210, 30));

        txt_tel.setBackground(new java.awt.Color(13, 71, 161));
        txt_tel.setForeground(new java.awt.Color(255, 255, 255));
        txt_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 30));

        txt_alias.setBackground(new java.awt.Color(13, 71, 161));
        txt_alias.setForeground(new java.awt.Color(255, 255, 255));
        txt_alias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_alias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_alias, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 210, 30));

        txt_pass.setBackground(new java.awt.Color(13, 71, 161));
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 210, 30));

        cmb_estatus.setBackground(new java.awt.Color(13, 71, 161));
        cmb_estatus.setForeground(new java.awt.Color(255, 255, 255));
        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Tecnico" }));
        cmb_estatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 210, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int validacion = 0,permiso_cmb;
        String nombre,direccion,telefono,alias,pass,estatus = "";
        
        nombre = txt_nom.getText().trim();
        direccion = txt_dir.getText().trim();
        telefono = txt_tel.getText().trim();
        alias = txt_alias.getText().trim();
        pass = txt_pass.getText().trim();
        permiso_cmb = cmb_estatus.getSelectedIndex()+1;
        
        if(nombre.equals("")){
            validacion++;
        }
        if(direccion.equals("")){
            validacion++;
        }
        if(telefono.equals("")){
            validacion++;
        }
        if(alias.equals("")){
            validacion++;
        }
        if(pass.equals("")){
            validacion++;
        }
        if(permiso_cmb == 1){
            estatus = "Administrador";
        }else if(permiso_cmb == 2){
            estatus = "Tecnico";
        }
        
        if (validacion == 0) {
            
            try {
                Connection con = Conectar.DataBase();
                PreparedStatement pre = con.prepareStatement(
                        "select alias from usuarios where alias = '" + alias + "' and not id_usuario = '" + ID + "'");
                ResultSet res = pre.executeQuery();
                
                if(res.next()){
                    JOptionPane.showMessageDialog(null, "el alias ya existe.");
                    con.close();
                }else{
                    
                    Connection cn = Conectar.DataBase();
                    PreparedStatement pst = cn.prepareStatement(
                            "update usuarios set nombre_usuario=?,direccion=?,telefono=?,alias=?,pass=?,estatus=?"
                                    + "where id_usuario = '" + ID + "'");
                    
                    pst.setString(1,nombre);
                    pst.setString(2,direccion);
                    pst.setString(3,telefono);
                    pst.setString(4,alias);
                    pst.setString(5,pass);
                    pst.setString(6,estatus);
                    
                    pst.executeUpdate();
                    cn.close();
                    JOptionPane.showMessageDialog(null, "actualizacion exitosa.");
                    this.dispose();
                    
                }
                
            } catch (SQLException e) {
                System.err.println("error al actualizar " + e);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "debes completar todos los campos");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_alias;
    private javax.swing.JTextField txt_dir;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
