/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import java.sql.*;
import conexion.Conectar;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class MovimientoProducto extends javax.swing.JFrame {

    String user,producto;
    int stock;
    
    public MovimientoProducto() {
        initComponents();
        user = Login.user;
        producto = StockTec.producto;
        setSize(600,400);
        setTitle("Movimiento de producto - sesion de " + user);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection cn = Conectar.DataBase();
            PreparedStatement pst = cn.prepareStatement(
                    "select tipo, marca, modelo, cantidad from productos where modelo = '" + producto + "'");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                txt_tipo.setText(rs.getString("tipo"));
                txt_marca.setText(rs.getString("marca"));
                txt_modelo.setText(rs.getString("modelo"));
                stock = rs.getInt("cantidad");
            }
            cn.close();
            
        } catch (SQLException e) {
            System.err.println("error al cargar los datos " + e);
        }
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LLaves.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tipo = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        btn_compras = new javax.swing.JButton();
        btn_ventas = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tipo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modelo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        txt_tipo.setEditable(false);
        txt_tipo.setBackground(new java.awt.Color(13, 71, 161));
        txt_tipo.setForeground(new java.awt.Color(255, 255, 255));
        txt_tipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 30));

        txt_marca.setEditable(false);
        txt_marca.setBackground(new java.awt.Color(13, 71, 161));
        txt_marca.setForeground(new java.awt.Color(255, 255, 255));
        txt_marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_marca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 210, 30));

        txt_modelo.setEditable(false);
        txt_modelo.setBackground(new java.awt.Color(13, 71, 161));
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 210, 30));

        txt_cantidad.setBackground(new java.awt.Color(13, 71, 161));
        txt_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        txt_cantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 210, 30));

        btn_compras.setBackground(new java.awt.Color(0, 51, 204));
        btn_compras.setForeground(new java.awt.Color(255, 255, 255));
        btn_compras.setText("Compra");
        btn_compras.setBorder(null);
        btn_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 210, 30));

        btn_ventas.setBackground(new java.awt.Color(0, 51, 204));
        btn_ventas.setForeground(new java.awt.Color(255, 255, 255));
        btn_ventas.setText("Venta");
        btn_ventas.setBorder(null);
        btn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 210, 30));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventasActionPerformed
        String tipo,marca,modelo,cant_st;
        int stock_actual = 0, cant_int = 0;
        
        tipo = txt_tipo.getText().trim();
        marca = txt_marca.getText().trim();
        modelo = txt_modelo.getText().trim();
        cant_st = txt_cantidad.getText().trim();
        
        cant_int = Integer.parseInt(cant_st);
        stock_actual = stock - cant_int;
        
        try {
            Connection cn = Conectar.DataBase();
            PreparedStatement pst = cn.prepareStatement(
                    "update productos set tipo=?, marca=?, modelo =?, cantidad=?, responsable=?"
                            + " where modelo = '" + producto + "'");
            
            pst.setString(1, tipo);
            pst.setString(2, marca);
            pst.setString(3, modelo);
            pst.setInt(4, stock_actual);
            pst.setString(5, user);
            
            pst.executeUpdate();
            cn.close();
            JOptionPane.showMessageDialog(null, "registro de venta exitoso.");
            this.dispose();
            
        } catch (SQLException e) {
            System.err.println("error al actualizar los datos de venta " + e);
        }
        
    }//GEN-LAST:event_btn_ventasActionPerformed

    private void btn_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprasActionPerformed
        String tipo,marca,modelo,cant_st;
        int stock_actual = 0, cant_int = 0;
        
        tipo = txt_tipo.getText().trim();
        marca = txt_marca.getText().trim();
        modelo = txt_modelo.getText().trim();
        cant_st = txt_cantidad.getText().trim();
        
        cant_int = Integer.parseInt(cant_st);
        stock_actual = stock + cant_int;
        
        try {
            Connection cn = Conectar.DataBase();
            PreparedStatement pst = cn.prepareStatement(
                    "update productos set tipo=?, marca=?, modelo =?, cantidad=?, responsable=?"
                            + " where modelo = '" + producto + "'");
            
            pst.setString(1, tipo);
            pst.setString(2, marca);
            pst.setString(3, modelo);
            pst.setInt(4, stock_actual);
            pst.setString(5, user);
            
            pst.executeUpdate();
            cn.close();
            JOptionPane.showMessageDialog(null, "registro de venta exitoso.");
            this.dispose();
            
        } catch (SQLException e) {
            System.err.println("error al actualizar los datos de venta " + e);
        }
    }//GEN-LAST:event_btn_comprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimientoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimientoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimientoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimientoProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_compras;
    private javax.swing.JButton btn_ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
